apiVersion: v1
kind: Secret
metadata:
  name: dbdetails
type: Opaque
data:
  CONNECTION_STRING: RHJpdmVyPXtPREJDIERyaXZlciAxNyBmb3IgU1FMIFNlcnZlcn07U2VydmVyPXRjcDpkZXZvcHNpbnNpZGVyc3Nydi5kYXRhYmFzZS53aW5kb3dzLm5ldCwxNDMzO0RhdGFiYXNlPXRvZG9hcHA7VWlkPWRldm9wc2FkbWluO1B3ZD1QQHNzdzAxcmRAMTIzO0VuY3J5cHQ9eWVzO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9bm87Q29ubmVjdGlvbiBUaW1lb3V0PTMwOw==

